const products = [
  {
    id: "1",
    title: "PlayStation 56",
    image: "../images/ps5.jpg",
    description: "Playstation 5 description",
    brand: "Sony",
    category: "Electronics",
    price: 300.59,
    countInStock: 12,
    rating: 4,
    numReviews: 11,
  },
  {
    id: "2",
    title: "Headphone",
    image: "../images/headphone.jpg",
    description: "Headphone description",
    brand: "Samsung",
    category: "Electronics",
    price: 99.59,
    countInStock: 12,
    rating: 3.5,
    numReviews: 20,
  },
  {
    id: "3",
    title: "MacBook",
    image: "../images/macbook.jpg",
    description: "MacBook description",
    brand: "Apple",
    category: "Electronics",
    price: 1000.59,
    countInStock: 12,
    rating: 4,
    numReviews: 11,
  },
  {
    id: "4",
    title: "Alexa",
    image: "../images/alexa.jpg",
    description: "Headphone description",
    brand: "Amazon",
    category: "Electronics",
    price: 99.59,
    countInStock: 12,
    rating: 2,
    numReviews: 20,
  },
];

export default products;
